---
title: Configure New Users
description: Runs the new user setup script in each new user's context until dynamic settings are applied successfully
actions:
  - !registryValue:
    path: 'HKU\AME_UserHive_Default\SOFTWARE\Microsoft\Windows\CurrentVersion\RunOnce'
    value: 'RunScript'
    operation: delete
  - !registryValue:
    path: 'HKU\AME_UserHive_Default\SOFTWARE\Microsoft\Windows\CurrentVersion\Run'
    value: 'SystemConfigNewUserSetup'
    data: |
      powershell -EP Bypass -NoP & """$([Environment]::GetFolderPath('Windows'))\SystemRuntime\Scripts\ApplyNewUserConfiguration.ps1"""
    type: REG_SZ
